### ISSUE TITLE
Getting an error with every attempt to search for a new anime show to add.

### ISSUE THREAD

**Issue by cobra2** [groenlid/xdm-anime-plugin-repo#2]
Just tried playing around with this today. I'm getting a connection refused from the groenlid.no-ip.org api call. When I switch back to api.urani.me i just get garbage. I'm not daft enough in python to fix this. 

excerpt from log:

Error: HTTPConnectionPool(host='groenlid.no-ip.org', port=80): Max retries exceeded with url: /api/search?q=freezing (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

Traceback (most recent call last):
  File "/home/someone/src/XDM/xdm/plugins/meta.py", line 159, in outer
    return run(_args, *_kwargs)
  File "/home/someone/src/XDM/plugins/Provider/Uranime-de_uranime_uranime-0_2/uranime.py", line 28, in searchForElement
    r = requests.get(url, params=payload)
  File "/home/someone/src/XDM/lib/requests/api.py", line 55, in get
    return request('get', url, *_kwargs)
  File "/home/someone/src/XDM/lib/requests/api.py", line 44, in request
    return session.request(method=method, url=url, *_kwargs)
  File "/home/someone/src/XDM/lib/requests/sessions.py", line 279, in request
    resp = self.send(prep, stream=stream, timeout=timeout, verify=verify, cert=cert, proxies=proxies)
  File "/home/someone/src/XDM/lib/requests/sessions.py", line 373, in send
    r = adapter.send(request, **kwargs)
  File "/home/someone/src/XDM/lib/requests/adapters.py", line 206, in send
    raise ConnectionError(e)
ConnectionError: HTTPConnectionPool(host='groenlid.no-ip.org', port=80): Max retries exceeded with url: /api/search?q=freezing (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

Traceback:
Traceback (most recent call last):
  File "/home/someone/src/XDM/xdm/plugins/meta.py", line 166, in outer
    log.error("Error during %s of %s \nError: %s\n\n%s\nNew value:%s" % (run.**name**, caller_name, ex, tb, out), traceback=tb, new_out=out, exception=ex)
  File "/home/someone/src/XDM/xdm/classes.py", line 226, in **str**
    return '%s(%s)[%s] %s' % (self.type, self.mediaType, self.get_id(), self.getName())
  File "/home/someone/src/XDM/xdm/classes.py", line 275, in **getattribute**
    return BaseModel.**getattribute**(self, name)
  File "/home/someone/src/XDM/lib/peewee.py", line 509, in **get**
    return self.get_object_or_id(instance)
  File "/home/someone/src/XDM/lib/peewee.py", line 504, in get_object_or_id
    raise self.rel_model.DoesNotExist
MediaTypeDoesNotExist

**Comment by groenlid** [comment]
Sorry for the late reply.

Try to update to version 0.3 of uranime and anime media type :+1:
There is still a bug where XDM searches for the wrong query on indexers. It seems to include the thumbnail path and other stuff in the query.

``` md
q=Carmine+1++29433+http%3A%2F%2Furani.me%2Fattachments%2Fepisodes%2F1278%2F29433.jpg&t=search
```

**Comment by cobra2** [comment]
SWEET! It's working now. You sir have just scratched my itch.
